name = "redirect-maintenance"
type = "javascript"
compatibility_date = "2022-01-31"

account_id = "acf825cc392e96dca126ee7e7f39e228"
zone_id = "dc3b4dce36437ddabcc6cdcc2d1019f0"

workers_dev = false
routes = [
    "asf.starry.blue/*",
    "atmos.starry.blue/*",
    "apps.starry.blue/*",
    "dns.starry.blue/*",
    "paste.starry.blue/*",
    "www.starry.blue/*",
]
